#!/usr/bin/env bash
# Rebuild the gopher model with Blender and inline it into the web game.
#   ./build.sh            # export GLB + preview renders + web/gopher-model.js
#   ./build.sh --no-render
set -euo pipefail
cd "$(dirname "$0")"

BLENDER="${BLENDER:-/Applications/Blender.app/Contents/MacOS/Blender}"
RENDER_ARGS=(--render assets/gopher-preview)
[[ "${1:-}" == "--no-render" ]] && RENDER_ARGS=()

"$BLENDER" -b --python blender/gopher.py -- --out assets/gopher.glb ${RENDER_ARGS[@]+"${RENDER_ARGS[@]}"} \
  | grep -E "GOPHER_|Error|Traceback" || true

# The game is opened straight from disk (file://), where fetch() of a .glb is blocked,
# so the model ships as a base64 string inside a plain <script> file.
python3 - <<'PY'
import base64, pathlib
glb = pathlib.Path("assets/gopher.glb").read_bytes()
b64 = base64.b64encode(glb).decode()
out = pathlib.Path("web/gopher-model.js")
out.parent.mkdir(exist_ok=True)
out.write_text(
    "// Generated by build.sh from assets/gopher.glb -- do not edit by hand.\n"
    f'window.GOPHER_GLB_B64 = "{b64}";\n'
)
print(f"wrote {out} ({len(glb)//1024} KB glb, {len(b64)//1024} KB base64)")
PY
