#!/usr/bin/env python3
"""Inline every assets/*.glb into web/gopher-model.js as base64.

The game is opened straight from disk (file://), where fetch() of a .glb is
blocked, so the models ship as strings inside a plain <script> file:

    window.GOPHER_MODELS = { "<name>": "<base64>", ... }   # name = file stem
    window.GOPHER_GLB_B64 = GOPHER_MODELS["gopher"]        # legacy alias

Run from anywhere; paths are resolved relative to the repository root.
"""
import base64
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT = ROOT / "web" / "gopher-model.js"


def main() -> int:
    glbs = sorted(ASSETS.glob("*.glb"))
    if not glbs:
        print(f"no .glb files in {ASSETS}", file=sys.stderr)
        return 1

    lines = [
        "// Generated by tools/embed_models.py from assets/*.glb -- do not edit by hand.",
        "window.GOPHER_MODELS = {",
    ]
    total = 0
    for path in glbs:
        data = path.read_bytes()
        total += len(data)
        lines.append(f"  {json.dumps(path.stem)}: {json.dumps(base64.b64encode(data).decode())},")
        print(f"  {path.name}: {len(data) // 1024} KB")
    lines += [
        "};",
        "// Backwards compatibility with the first version of the game.",
        'window.GOPHER_GLB_B64 = window.GOPHER_MODELS["gopher"];',
        "",
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(glbs)} models, {total // 1024} KB of glb)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
